triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-03 14:27:08.305842+00:00
  name: retrain models hourly
  pipeline_uuid: automatic_retraining
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    allow_blocks_to_fail: true
    create_initial_pipeline_run: true
    skip_if_previous_running: true
  sla: null
  start_time: 2024-06-03 22:00:00+00:00
  status: active
  token: e81f0494aeb5453e81dbb335add98eeb
  variables: {}
